<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-JT7PQM5" ignored="0" name="Test2" tests="1" failures="1" timestamp="16 Sep 2017 11:12:19 GMT" time="13.752" errors="0">
  <testcase name="@AfterTest afterClass" time="5.002" classname="offline_Testing_Pro.Offline_Web_App">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at offline_Testing_Pro.Offline_Web_App.afterClass(Offline_Web_App.java:110)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest afterClass -->
  <testcase name="f" time="0.005" classname="offline_Testing_Pro.Offline_Web_App">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at offline_Testing_Pro.Offline_Web_App.f(Offline_Web_App.java:65)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- f -->
</testsuite> <!-- Test2 -->
